[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = "dist"
    target = "assets/js/vendor/leaflet"
    includeFiles = "leaflet.js"
  [[module.mounts]]
    source = "dist/leaflet.css"
    target = "assets/scss/vendor/leaflet/leaflet.scss"
  [[module.mounts]]
    source = "dist/images"
    target = "static/css/images"
    includeFiles = "*.png"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'
