baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-leaflet'

[module]
  replacements = 'github.com/gethinode/mod-leaflet -> ../..'
  [[module.imports]]
    path = "github.com/gethinode/mod-leaflet"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "dist/leaflet.scss"
    target = "static/leaflet.css"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.imports.mounts]]
    source = "assets/js/leaflet-map.js"
    target = "static/leaflet-map.js"
